// https://en.wikipedia.org/wiki/Box-drawing_characters
// https://www.w3.org/TR/xml-entity-names/025.html
export enum Symbols {
    UpperHalfBlock = '▀',
    FullBlock = '█',
    LightShade = '░',
    MediumShade = '▒',
    DarkShade = '▓',
    SquareOutlined = '▣',
    SquareGrid = '▦',
    SquareWhite = '□',
    QuadrantBottomLeft = '▖',
    QuadrantTopLeft = '▘',
    QuadrantBottomRight = '▗',
    QuadrantTopRight = '▝',
    QuadrantForwardSlash = '▞',
    QuadrantBackwardSlash = '▚',
    QuadrantInverseBottomLeft = '▜',
    QuadrantInverseTopLeft = '▟',
    QuadrantInverseBottomRight = '▛',
    QuadrantInverseTopRight = '▙',
    DiamondOutlined = '◈',
    DiamondWhite = '◇',
    DottedCircle = '◌',
    Circle = '○',
    CircleDoubleOutline = '◎',
    CircleWithCross = '⦻',
    ParallelogramOutline = '▱',
    RhombusOutline = '◊',
    Ellipsis = '…',
    Lemniscate = '∞',
    CircleQuarterTopRight = '◔',
    SquareQuadrantTopRight = '◳',
    TriangleDownSmall = '▾',
    TriangleLeftSmall = '◂',
    TriangleRightSmall = '▸',
    TriangleUpOutline = '△',
    TriangleDown = '▼',
    HalfFilledSquareLeft = '◧',
}
