// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,command:12, state:34, true:48, false:48, when:60}
export const parser = LRParser.deserialize({
  version: 14,
  states: ")lQYQPOOOeQPO'#C`OjQPO'#C{OoQPO'#C|OOQO'#C_'#C_OOQO'#C}'#C}QYQPOOOtQPO,58zOtQPO,59gO!bQPO'#CoOwQPO,59hOOQO-E6{-E6{O!oQPO'#CeO!tQPO'#CjOOQO1G.f1G.fOwQPO1G.fOOQO1G/R1G/ROwQPO1G/RO#SQPO'#DQO#XQPO,59ZOOQO1G/S1G/SOOQO'#Cg'#CgO#vQPO'#CfO#{QPO,59PO$TQPO'#ClO$YQPO'#CoO$aQPO'#CnO$rQPO'#CyOOQO'#Ck'#CkOOQO'#DP'#DPO%TQPO,59UOOQO,59U,59UOOQO7+$Q7+$QOOQO7+$m7+$mOOQO,59l,59lOOQO-E7O-E7OOOQO,59Q,59QO!oQPO'#DOO%cQPO1G.kOOQO1G.k1G.kOOQO,59W,59WO$rQPO,59dO%kQPO'#CpOOQO,59Y,59YO%rQPO'#CrOOQO'#Cs'#CsO$rQPO'#CwOOQO'#Cq'#CqOwQPO,59eOOQO-E6}-E6}OOQO1G.p1G.pOOQO,59j,59jOOQO-E6|-E6|OOQO7+$V7+$VOOQO1G/O1G/OOOQO,59[,59[O&fQPO,59[O&nQPO,59cOOQO1G/P1G/PO$rQPO'#DRO&sQPO1G.vOOQO1G.v1G.vOOQO1G.}1G.}OOQO,59m,59mOOQO-E7P-E7POOQO7+$b7+$b",
  stateData: "&{~OxOSPOS~OUPOaQOnRO~OTVO~OTWO~OTXO~OW[O]]O~OzbOWcXTcX[cXacXncX~O]cXVcXycX~P|OTeO~OTiO[oOahOnkO~OTrO~OzbO]caTcaWca[caacancaVcayca~OTtO~OVwOyuO~OTxO~O{yO~P|OWzOTbX[bXabXnbX~OTXOW!OOh}Oi!POj!PO~OTiO[!SOahOnkO~OV!VOyuO~OV!XO~P$rO]bX]fXTfX[fXafXnfXVbXVfXybXyfX~P$aOV!_Oy!]O~OV!`O~OV!cOy!]O~O",
  goto: "$jvPPPw{PPPP!P!V!]PP!a!s!wP!{#W#f#j#P#PPPP#P!w!wP{{#y$P$V$]$dTTOUTSOUQ_VRaWQg[R!TuTf[uQ^VQ`WQdYQp_QqaR![!QTm]nTl]nSl]nZ!Pkyz!O!]QYRSj]nZ|kyz!O!]T{j|Q!QkQ!WyQ!YzQ!Z!OR!a!]QUORZUQvgR!UvQn]R!RnScXiRscQ!^!YR!b!^",
  nodeNames: "⚠ LineComment Program Declaration CommandDeclaration Identifier Declkw ) ( ArgumentsDeclaration ArgumentDeclaration Typename } { StatementBlock Statement SetStateCommand Declkw ProcedureCall NestedIdentifier ArgumentsList Expression VariableRead BoolLiteral Boolkw StringLiteral IntegerLiteral NestedExpression VariableAssignment ConditionalStatement Declkw StateDeclaration EventDeclaration",
  maxTerm: 43,
  nodeProps: [
    ["openedBy", 7,"(",12,"{"],
    ["closedBy", 8,")",13,"}"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 5,
  tokenData: "&S~RbXY!ZYZ!Z]^!Zpq!Zrs!lst$Yxy$qyz$v|}${}!O%Q!O!P%`!Q![%W!_!`%e!c!}%j#R#S%j#T#o%j#o#p%x#q#r%}~!`Sx~XY!ZYZ!Z]^!Zpq!Z~!oVOr!lrs#Us#O!l#O#P#Z#P;'S!l;'S;=`$S<%lO!l~#ZOi~~#^RO;'S!l;'S;=`#g;=`O!l~#jWOr!lrs#Us#O!l#O#P#Z#P;'S!l;'S;=`$S;=`<%l!l<%lO!l~$VP;=`<%l!l~$_SP~OY$YZ;'S$Y;'S;=`$k<%lO$Y~$nP;=`<%l$Y~$vOW~~${OV~~%QOy~~%TP!Q![%W~%]Pj~!Q![%W~%eOz~~%jO{~~%oRT~!c!}%j#R#S%j#T#o%j~%}O]~~&SO[~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 5, get: (value: keyof typeof spec_Identifier) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
