// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,command:10, state:30, yes:44, no:44, not:56, and:68, or:68, xor:68, when:74, default:78}
export const parser = LRParser.deserialize({
  version: 14,
  states: ",YQYQPOOOeQPO'#C_OjQPO'#DSOoQPO'#DUOOQO'#D_'#D_OOQO'#DV'#DVQYQPOOOtQPO,58yO|QPO,59nO!XQPO'#CnOwQPO,59pOOQO-E7T-E7TO!aQPO'#CdO!fQPO'#CiOOQO1G.e1G.eOwQPO1G.eOOQO1G/Y1G/YOwQPO1G/YO!tQPO1G/YO!|QPO'#DYO#RQPO,59YOOQO1G/[1G/[OOQO'#Cf'#CfO#jQPO'#CeO#oQPO,59OO$]QPO'#CnO$dQPO'#CmO$uQPO'#CjO$uQPO'#DQOOQO'#Da'#DaOOQO'#DX'#DXO%dQPO,59TOOQO,59T,59TOOQO7+$P7+$POOQO7+$t7+$tOwQPO7+$tOOQO,59t,59tOOQO-E7W-E7WOOQO,59P,59PO!aQPO'#DWO%rQPO1G.jOOQO1G.j1G.jO$uQPO,59kO%zQPO'#CoOOQO,59X,59XO&RQQO'#CnO(aQQO'#CmOOQO'#Cq'#CqOOQO'#Cw'#CwO$uQPO'#CvO*[QQO,59UO$uQPO'#DnOOQO'#Cl'#ClO*lQQO,59lOOQO-E7V-E7VOOQO1G.o1G.oOOQO<<H`<<H`OOQO,59r,59rOOQO-E7U-E7UOOQO7+$U7+$UO*sQQO1G/VOOQO,59Z,59ZO+TQQO,59ZO+_QQO,59YO,_QQO,59bOOQO'#Cz'#CzOOQO'#C{'#C{OOQO'#C|'#C|OOQO'#C}'#C}O$uQPO,59eO$uQPO,59eO$uQPO,59eO$uQPO,59eO,xQQO,5:YOOQO1G/W1G/WO$uQPO'#DZO-PQPO1G.uOOQO1G.u1G.uOOQO1G/P1G/PO.`QQO1G/PO.jQQO1G/PO.tQQO1G/POOQO1G/t1G/tO/bQQO,59uOOQO-E7X-E7XOOQO7+$a7+$a",
  stateData: "/l~O!QOSPOS~OTPO_QOuRO~OSVO~OSWO~OSXO~OV[O[]O~OV[O[]OwaO~O!UcO[bX~OSfO~OSiOZpO_kOulO~O[]OwsO~OStO~O!UcO[baSbaVbaZba_bauba~OSvO~OUyO!SwO~O!UcOSbXVbXZbX_bXubX~O!czO~P#wOV{OSaXZaX_aXuaX~OS}OV!TOf!POg!UOh!UOi!UOl!QO!V!QO!W!QO~OSiOZ!XO_kOulO~OU!]O!SwO~OU!_O~P$uOSdXZdX_dXrbXrdXudX!VbX!VdX!WbX!WdX!XbX!XdX!YbX!YdX!ZbX!ZdX![bX![dX!]bX!]dX!^bX!^dX!_bX!_dX!`bX!`dX!abX!adX[bX[dXUbXUdX!SbX!SdX~P#wOraX!VaX!WaX!XaX!YaX!ZaX![aX!]aX!^aX!_aX!`aX!aaX[aXUaX!SaX~P$dOr!fO!V!dO!W!dO!X!cO!Y!cO!Z!cO![!eO!]!eO!^!eO!_!eO!`!eO!a!eO~OS^aZ^a_^au^a~P)dO[]O~P)dOSsiZsi_siusi~P)dOU!oO!S!mO~P)dOrba!Vba!Wba!Xba!Yba!Zba![ba!]ba!^ba!_ba!`ba!abaUba!Sba~P#ROSjaZja_jauja[jaUja!Sja~P)dOU!tO~P)dOU!wO!S!mO~O!X!cO!Y!cO!Z!cOSmiZmi_mirmiumi![mi!]mi!^mi!_mi!`mi!ami[miUmi!Smi~O!Vmi!Wmi~P-XO!V!dO!W!dO~P-XOSmiZmi_mirmiumi[miUmi!Smi~P)gOU}a!S}a~P)dO",
  goto: "'W!cPPP!dPPPP!h!n!tPP!x#`P#d$V$h$|$Z$ZPPPP$Z%QP$Z%_%k%v&QP#`#`P!dP!d&Z&a&g&m&xPPP'OP'SPPPPPPPPPPPP$ZTSOUQ_VRbWQh[R!ZwTg[wQ^VQ`WQeYQq_SrabQ!YsR!l!VTm]oQ!SkQ!VlQ!^zQ!`{Q!b!RQ!k!TQ!p!gQ!q!hQ!r!iQ!s!jR!u!mSm]og!Uklz{!R!T!g!h!i!j!mQYRSj]og!Oklz{!R!T!g!h!i!j!mT|j!Og!Rklz{!R!T!g!h!i!j!me!g!S!V!^!`!b!k!q!r!s!uc!h!S!V!^!`!b!k!r!s!ua!i!S!V!^!`!b!k!s!u_!j!S!V!^!`!b!k!uQUORZUQxhR![xQo]R!WoSdXiSud!aR!a}Q!n!`R!v!nTTOUTn]o",
  nodeNames: "⚠ LineComment Program CommandDeclaration Identifier Declkw ) ( ArgumentsDeclaration ArgumentDeclaration Typename } { StatementBlock SetStateCommand Declkw Expression ProcedureCall NestedIdentifier ArgumentsList VariableRead BoolLiteral Boolkw StringLiteral IntegerLiteral StateNameLiteral UnaryExpression UnaryOperator UnaryOp BinaryExpression BinaryOperatorMul BinaryOperatorSum BinaryOperatorCmp BinaryOperatorLogic BinOpLogic VariableAssignment ConditionalStatement Declkw StateDeclaration Defaultkw EventDeclaration",
  maxTerm: 65,
  nodeProps: [
    ["openedBy", 6,"(",11,"{"],
    ["closedBy", 7,")",12,"}"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 5,
  tokenData: "(g~RiXY!pYZ!p]^!ppq!prs#Rst$ouv%Wxy%]yz%bz{%g{|%l|}%q}!O%v!O!P%{!P!Q&Q!Q![&_![!]&g!^!_'R!_!`'`!`!a'm!c!}'z#R#S'z#T#o'z#o#p(]#q#r(b~!uS!Q~XY!pYZ!p]^!ppq!p~#UVOr#Rrs#ks#O#R#O#P#p#P;'S#R;'S;=`$i<%lO#R~#pOg~~#sRO;'S#R;'S;=`#|;=`O#R~$PWOr#Rrs#ks#O#R#O#P#p#P;'S#R;'S;=`$i;=`<%l#R<%lO#R~$lP;=`<%l#R~$tSP~OY$oZ;'S$o;'S;=`%Q<%lO$o~%TP;=`<%l$o~%]O!Z~~%bOV~~%gOU~~%lO!X~~%qO!W~~%vO!S~~%{O!V~~&QO!U~~&VP!Y~!_!`&Y~&_O!a~~&dPh~!Q![&_~&jR!c!}&s#R#S&s#T#o&s~&xRi~!c!}&s#R#S&s#T#o&s~'WP![~!_!`'Z~'`O!_~R'eP!cP!_!`'hQ'mO!`Q~'rP!]~!_!`'u~'zO!^~~(PSS~!Q!['z!c!}'z#R#S'z#T#o'z~(bO[~~(gOZ~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  specialized: [{term: 4, get: (value: keyof typeof spec_Identifier) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
