// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,command:10, state:30, yes:44, no:44, not:58, and:70, or:70, xor:70, when:76, default:80}
export const parser = LRParser.deserialize({
  version: 14,
  states: ",lQYQPOOOeQPO'#C_OjQPO'#DTOoQPO'#DVOOQO'#D`'#D`OOQO'#DW'#DWQYQPOOOtQPO,58yO|QPO,59oO!XQPO'#CnOwQPO,59qOOQO-E7U-E7UO!aQPO'#CdO!fQPO'#CiOOQO1G.e1G.eOwQPO1G.eOOQO1G/Z1G/ZOwQPO1G/ZO!tQPO1G/ZO!|QPO'#DZO#RQPO,59YOOQO1G/]1G/]OOQO'#Cf'#CfO#jQPO'#CeO#oQPO,59OO$]QPO'#CnO$dQPO'#CmO$uQPO'#CjO$uQPO'#DROOQO'#Db'#DbOOQO'#DY'#DYO%dQPO,59TOOQO,59T,59TOOQO7+$P7+$POOQO7+$u7+$uOwQPO7+$uOOQO,59u,59uOOQO-E7X-E7XOOQO,59P,59PO!aQPO'#DXO%rQPO1G.jOOQO1G.j1G.jO$uQPO,59lO%zQPO'#CoOOQO,59X,59XO&RQQO'#CnO(aQQO'#CmOOQO'#Cq'#CqO)dQQO'#CtOOQO'#Cx'#CxO$uQPO'#CwO+lQQO,59UO$uQPO'#DpOOQO'#Cl'#ClO+|QQO,59mOOQO-E7W-E7WOOQO1G.o1G.oOOQO<<Ha<<HaOOQO,59s,59sOOQO-E7V-E7VOOQO7+$U7+$UO,TQQO1G/WOOQO,59Z,59ZO,eQQO,59ZO,oQQO,59YO-oQPO,59aO-tQQO,59cOOQO'#C{'#C{OOQO'#C|'#C|OOQO'#C}'#C}OOQO'#DO'#DOO$uQPO,59fO$uQPO,59fO$uQPO,59fO$uQPO,59fO._QQO,5:[OOQO1G/X1G/XO$uQPO'#D[O.fQPO1G.uOOQO1G.u1G.uOOQO1G.{1G.{OOQO1G/Q1G/QO/uQQO1G/QO0PQQO1G/QO0ZQQO1G/QOOQO1G/v1G/vO0wQQO,59vOOQO-E7Y-E7YOOQO7+$a7+$a",
  stateData: "1R~O!ROSPOS~OTPO_QOvRO~OSVO~OSWO~OSXO~OV[O[]O~OV[O[]OxaO~O!VcO[bX~OSfO~OSiOZpO_kOvlO~O[]OxsO~OStO~O!VcO[baSbaVbaZba_bavba~OSvO~OUyO!TwO~O!VcOSbXVbXZbX_bXvbX~O!ezO~P#wOV{OSaXZaX_aXvaX~OS}OV!UOf!POg!VOj!VOm!RO!W!QO!X!RO!Y!RO~OSiOZ!YO_kOvlO~OU!^O!TwO~OU!`O~P$uOSdXZdX_dXsbXsdXvdX!XbX!XdX!YbX!YdX!ZbX!ZdX![bX![dX!]bX!]dX!^bX!^dX!_bX!_dX!`bX!`dX!abX!adX!bbX!bdX!cbX!cdX[bX[dXUbXUdX!TbX!TdX~P#wOsaX!XaX!YaX!ZaX![aX!]aX!^aX!_aX!`aX!aaX!baX!caX[aXUaX!TaX~P$dO!V!cOShXZhX_hXshXvhX!XhX!YhX!ZhX![hX!]hX!^hX!_hX!`hX!ahX!bhX!chX[hXUhX!ThX~Os!hO!X!fO!Y!fO!Z!eO![!eO!]!eO!^!gO!_!gO!`!gO!a!gO!b!gO!c!gO~OS^aZ^a_^av^a~P*tO[]O~P*tOStiZti_tivti~P*tOU!qO!T!oO~P*tOsba!Xba!Yba!Zba![ba!]ba!^ba!_ba!`ba!aba!bba!cbaUba!Tba~P#RO!W!rO~OSkaZka_kavka[kaUka!Tka~P*tOU!wO~P*tOU!zO!T!oO~O!Z!eO![!eO!]!eOSniZni_nisnivni!^ni!_ni!`ni!ani!bni!cni[niUni!Tni~O!Xni!Yni~P.nO!X!fO!Y!fO~P.nOSniZni_nisnivni[niUni!Tni~P*wOU!Oa!T!Oa~P*tO",
  goto: "'Y!ePPP!fPPPP!j!p!vPP!z#bP#f$X$j%O$]$]PP$]$]P$]%SP$]%a%m%x&SP#b#bP!fP!f&]&c&i&o&zPPP'QP'UPPPPPPPPPPPPP$]TSOUQ_VRbWQh[R![wTg[wQ^VQ`WQeYQq_SrabQ!ZsR!n!WTm]oQ!TkQ!WlQ!_zQ!a{Q!d!SQ!m!UQ!s!iQ!t!jQ!u!kQ!v!lR!x!oSm]og!Vklz{!S!U!i!j!k!l!oQYRSj]og!Oklz{!S!U!i!j!k!l!oT|j!Og!Sklz{!S!U!i!j!k!l!oe!i!T!W!_!a!d!m!t!u!v!xc!j!T!W!_!a!d!m!u!v!xa!k!T!W!_!a!d!m!v!x_!l!T!W!_!a!d!m!xQUORZUQxhR!]xQo]R!XoSdXiSud!bR!b}Q!p!aR!y!pTTOUTn]o",
  nodeNames: "⚠ LineComment Program CommandDeclaration Identifier Declkw ) ( ArgumentsDeclaration ArgumentDeclaration Typename } { StatementBlock SetStateCommand Declkw Expression ProcedureCall NestedIdentifier ArgumentsList VariableRead BoolLiteral Boolkw StringLiteral IntegerLiteral FloatLiteral StateNameLiteral UnaryExpression UnaryOperator UnaryOp BinaryExpression BinaryOperatorMul BinaryOperatorSum BinaryOperatorCmp BinaryOperatorLogic BinOpLogic VariableAssignment ConditionalStatement Declkw StateDeclaration Defaultkw EventDeclaration",
  maxTerm: 67,
  nodeProps: [
    ["openedBy", 6,"(",11,"{"],
    ["closedBy", 7,")",12,"}"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 5,
  tokenData: "(g~RiXY!pYZ!p]^!ppq!prs#Rst$ouv%Wxy%]yz%bz{%g{|%l|}%q}!O%v!O!P%{!P!Q&Q!Q![&_![!]&g!^!_'R!_!`'`!`!a'm!c!}'z#R#S'z#T#o'z#o#p(]#q#r(b~!uS!R~XY!pYZ!p]^!ppq!p~#UVOr#Rrs#ks#O#R#O#P#p#P;'S#R;'S;=`$i<%lO#R~#pOg~~#sRO;'S#R;'S;=`#|;=`O#R~$PWOr#Rrs#ks#O#R#O#P#p#P;'S#R;'S;=`$i;=`<%l#R<%lO#R~$lP;=`<%l#R~$tSP~OY$oZ;'S$o;'S;=`%Q<%lO$o~%TP;=`<%l$o~%]O!]~~%bOV~~%gOU~~%lO!Z~~%qO!Y~~%vO!T~~%{O!X~~&QO!V~~&VP![~!_!`&Y~&_O!c~~&dP!W~!Q![&_~&jR!c!}&s#R#S&s#T#o&s~&xRj~!c!}&s#R#S&s#T#o&s~'WP!^~!_!`'Z~'`O!a~R'eP!eP!_!`'hQ'mO!bQ~'rP!_~!_!`'u~'zO!`~~(PSS~!Q!['z!c!}'z#R#S'z#T#o'z~(bO[~~(gOZ~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  specialized: [{term: 4, get: (value: keyof typeof spec_Identifier) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
